name: Run ML CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-ml-model:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout source code
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Setup Python 3.12.7
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.7"

    # 3️⃣ Cek environment
    - name: Check environment
      run: |
        python --version
        pip --version
        echo "Current directory:"
        pwd
        echo "Project structure:"
        ls -R

    # 4️⃣ Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 5️⃣ Run modelling (DATA SUDAH BERSIH)
    - name: Run ML Modelling
      working-directory: modeling
      run: |
        python modeling_bg.py

    # 6️⃣ Ambil MLflow run-id
    - name: Get MLflow Run ID
      run: |
        python - <<EOF
        from mlflow.tracking import MlflowClient

        client = MlflowClient()
        exp = client.get_experiment_by_name("CI_Modelling_Experiment")

        runs = client.search_runs(
            experiment_ids=[exp.experiment_id],
            order_by=["attributes.start_time DESC"],
            max_results=1
        )

        print("MLFLOW_RUN_ID:", runs[0].info.run_id)
        EOF
